server {
    # Port d'écoute pour le HTTPS
    listen 443 ssl;
    listen [::]:443 ssl;

    # Ton nom de domaine configuré dans le fichier hosts
    server_name lscheupl.42.fr;

    # Chemins vers les certificats générés dans le Dockerfile
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Protocoles de sécurité exigés par le sujet
    ssl_protocols TLSv1.2 TLSv1.3;

    # Dossier racine et fichiers par défaut
    root /var/www/wordpress;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    # Configuration pour passer les requêtes PHP au conteneur WordPress
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:9000;
    }
}